### ISSUE TITLE
[Sega CD] Special effects are glitchy in Chuck Rock II: Son of Chuck

### ISSUE THREAD

**Issue by jmaneyrol69** [libretro/Genesis-Plus-GX#298] opened 2022-05-16 09:24 UTC
**Description**

**Chuck Rock II: Son of Chuck** mega cd/sega cd version uses special effects specific to the SCD/MCD which are not rendered properly. This affects all rolling boulders, but also sprites such as the giant bird in Stage 2.

This bug is also present in other emulators/cores: lr-picodrive, pemu, Kega Fusion (Windows) and md.emu (Android)

**Game versions**

- Sega CD, US [!] (cue, bin)

**Screens**

| Giant Bird | Boulders | Boulder |
|---|---|---|
| ![Chuck Rock II - Son Of Chuck (u)-220516-102808](https://user-images.githubusercontent.com/45173285/168561362-d9fc13c6-2834-4c96-878b-22a4878cca9d.png) | ![Chuck Rock II - Son Of Chuck (u)-220516-103021](https://user-images.githubusercontent.com/45173285/168561363-51c99f89-39b4-44f2-92e3-2afe405778eb.png) | ![Chuck Rock II - Son Of Chuck (u)-220516-103042](https://user-images.githubusercontent.com/45173285/168561366-daa16686-e3fb-4e2b-8f7b-bab53316f59a.png) |

**Environment**

Version: Genesis Plus GX v1.7.4
Environment: Windows/Linux/Android

**Comment by ekeeke** [comment] 2022-05-29 16:49
I can confirm this is an emulation issue (not related to libretro port and surprisingly, indeed shared by all Mega CD software emulators).

Could you please close the issue in this repository and reopen it in https://github.com/ekeeke/Genesis-Plus-GX so I can keep track of it.

Thanks

**Comment by jmaneyrol69** [comment] 2022-05-30 09:49
Done!
Small update: I have found that [ares emulator](https://ares-emu.net/) seems to be the only one to render it properly (tested on EU version, US does not boot - but that's not a problem, the bug also appears with the EU versions on other emus).

**Comment by ekeeke** [comment] 2022-05-30 12:08
Thanks. Do not forget to close this issue to avoid issue duplication between repositories. Ideally, emulation issues should be reported in my repository so I can be more directly informed of them since I am the one usually fixing them and libretro specific issues should be reported here as they generally fall under libretro team responsibility.

**Closed** 2022-05-30 12:09 UTC
