### ISSUE TITLE
Add CHD support for Genesis Plus GX and Picodrive

### ISSUE THREAD

**Issue by ajshell1** [libretro/Genesis-Plus-GX#93] opened 2017-08-02 23:59 UTC
This is a follow-up to a [previous bounty](https://github.com/libretro/beetle-saturn-libretro/issues/31).

All I ask is that someone adds CHD support  to the Genesis Plus GX core.

I won't be posting a bounty to add CHD support to the PicoDrive. Someone else can do that if they really want to play all six Sega CD games that require the 32X expansion (Corpse Killer, Night Trap, Fahrenheit, Slam City, Supreme Warrior, and Surgical Strike*).

This will have a bounty of $15.

*Surgical Strike for the 32X was only released in Brazil and no dump of it can be found on the internet.

EDIT: There is hope for Surgical Strike! Some Brazilian guys are re-releasing it. They say that they will release an ISO of it on August 15 of 2017.

EDIT2: Because ekeeke doesn't want the money, I am changing this to a Geneis Plus GX and Picodrive bounty. Thus, whoever ports it to Picodrive will get all the money.

**Comment by rtissera** [comment] 2017-08-06 10:03
@ekeeke is it something which could be upstreamed ?

**Comment by ekeeke** [comment] 2017-08-06 11:34
Sure, depending how this is implemented and interfaces with current core. Ideally, this would be made optional like ogg file support.

**Comment by rtissera** [comment] 2017-08-06 11:42
OK good to know. The biggest burden is TOC rebuilding. I will try to have a
look after adding clean support to various mednafen cores.

**Comment by ekeeke** [comment] 2017-08-16 08:35
>The biggest burden is TOC rebuilding. I will try to have a look after adding clean support to various mednafen cores.

I actually started implementing it as a coding exercise. The hardest part was indeed to figure how to build the TOC since CHD documentation is quite scarce but I eventually managed to get how it works by reading MAME code (chdman.cpp, cdrom.cpp and chdcd.c) and integrated it in Genesis Plus GX code without much work. Still need to compile the whole thing and test/debug it but this does  not look like it will be much difficult.

**Comment by rtissera** [comment] 2017-08-16 09:28
@ekeeke Great!

Let me know if you have any issue and feel free to have a look at
CDAccess_CHD class in beetle pcfx or pce fast libretro cores as example of
doing that.

**Comment by p1pkin** [comment] 2017-08-16 12:52
its actually not hard at all to use CHD in your project using original MAME cdrom.h/cdrom.cpp: cdrom_open, cdrom_read_data, cdrom_read_subcode, cdrom_get_toc - that's all functions you will need to use. also it will handle not only CHD but all other image formats supported by MAME core (cue/bin, nrg, toc/bin etc)

on other hand, it is pain in the arse if you will use libchdr port instead ...

**Comment by rtissera** [comment] 2017-08-16 13:09
@p1pkin I was actually thinking adding helper functions from cdrom.cpp to libchdr in order to make it easier to use.

But it's always nice to see support and kind words ;)

**Comment by ekeeke** [comment] 2017-08-16 13:33
@p1pkin

MAME code is actually quite heavy and tied to its own structure definitions for CDROM, tracks, etc

It was actually much easier to use stripped-out C version of chd.c and cdrom.c from @rtissera and make a few modifications to my own code in cdd.c than reusing MAME abstraction and adapting my code for it.

**Comment by p1pkin** [comment] 2017-08-16 14:40
@ekeeke I see you point, indeed C version is more lightweight, if it matters for you target platforms.

I just trying to warn - it is not good idea to parse metadata tag in each emulator, but it have to be implemented in libchdr.
mainly because CHD format is not static, there couple of things planned to be implemented in future, like multisession CD support and few others. this is likely lead to change from CUE-like metadata TOC, to binary/RAW TOC, basically in the same form as it "stored" in CD lead-in subcode.
guess what will happen in this case ? - all emulators will have to change metadata TOC parsing routines to support newer chd images. doesn't look good eh ?
so, as was said above, in my honest opinion, this must be handled in chd library, instead of each emulator on its own.

**Comment by rtissera** [comment] 2017-08-16 14:50
@p1pkin Thanks for the valuable insight on the metadata parsing, I totally agree with you this should be added to libchdr.

The fact is that libchdr was initially written for solely use in redream and then I added it in libretro stuff. 
I will add the metadata parsing and high level cdrom TOC logic to the library and push updates to current implementations (so far only redream and beetle-*-libretro cores).

**Comment by ekeeke** [comment] 2017-08-20 12:12
@rtissera: there seems to be a lot of memory allocation (malloc) that never get freed when calling chd_close. Similarly, lzma_codec_free is defined but never called and there is a lot of "TODO" in many of the codec free functions. This seems it could cause some memory leak when loading consecutive. chd files.

Another thing I noticed is that chd->cache and chd->compare buffers are allocated with the size of a chunk but never get actually used by anything. It seems safe to remove these to save some RAM.

**Comment by rtissera** [comment] 2017-08-20 12:15
@ekeeke Yes definitely I will try to clean this up ASAP.

**Comment by ekeeke** [comment] 2017-08-20 19:53
If this can be some help, here is my modified version which should have all potential memory leaks fixed hopefully, as well as some unused stuff removed. Do whatever you want with it anddo not hesitate to tell me if you think I missed something.

[chd.zip](https://github.com/libretro/Genesis-Plus-GX/files/1237239/chd.zip)

I also had to modify a few header files to deal with multiple similar typedefs.

**Comment by rtissera** [comment] 2017-08-20 19:55
Oh thanks a lot, I will merge this in a couple o days.

**Comment by ekeeke** [comment] 2017-08-21 12:36
Beware it was not fully tested yet. I had to modify a change I made that was incorrect. To fix errors with subcode decompressing in CD FLAC codec interface, I had to replace 

`zlib_codec_init(cdfl,...`
&
`zlib_codec_free(cdfl);`

by
`zlib_codec_init(&cdfl->inflater,...`
&
`zlib_codec_free(&cdfl->inflater);`

in

`cdfl_codec_init()`
&
`cdfl_codec_free()`

So far, CHD support works in Genesis Plus GX except for audio tracks which only produce noise. I'm using an old version of chdman I had from 2012 with data track compressed with LZMA and audio tracks compressed with FLAC. Any idea where this could come from?

**Comment by p1pkin** [comment] 2017-08-21 12:43
chdman included in MAME distributive http://www.mamedev.org/release.html

**Comment by rtissera** [comment] 2017-08-22 20:45
@ekeeke I do remember some CHDMAN binaries floating around produce bad metadata (inducing TOC issues) but I do not this this is your issue. Have you tried byte-swapping FLAC decoded audio ?
I do remember seeing some code into MAME related to endianness on CDDA compressed tracks.

**Comment by ekeeke** [comment] 2017-08-22 21:29
Yes, that was actually the issue. I actually just fixed it before I got the opportunity to read your message ;-)

16-bit audio samples are indeed big-endian when uncompressed (while original CD-DA format is little endian). I figured it by comparing emulator PCM outputs when using CUE/BIN and CHD.

**Comment by rtissera** [comment] 2017-08-23 05:25
OK great! I will merge your fixes and try to improve libchdr adding high
level CD-ROM code for TOC handling.

**Comment by rtissera** [comment] 2017-08-23 08:39
@ekeeke Merged most of your changes into https://github.com/rtissera/libchdr/tree/ekeeke
I will test this against redream and beetle-*-libretro implementations and update  the branch accordingly.

**Comment by ekeeke** [comment] 2017-08-27 15:06
This commit https://github.com/ekeeke/Genesis-Plus-GX/commit/05dc8faa0419869438fc1a3c2b1741e87fea0178 adds CHD support in Genesis Plus GX repository.

This was tested fine with official Wii port and Retroarch Win32 port using a cue/bin (Super Strike Trilogy) converted to .chd with latest chdman version.

Please confirm it works for you and close this (this will need to be backported and compiled in libretro repository first)

@rtissera : to get FLAC decoding working on big endian platform (Wii), I needed to add the following defines in Makefile.Wii `-DCPU_IS_BIG_ENDIAN=1 -DWORDS_BIGENDIAN=1`
You might need to add these flags in Makefile.libretro for the various cores where you already implemented CHD support when they build for big endian platforms (such as Wii, WiiU, PS3,etc).

**Comment by twinaphex** [comment] 2017-08-27 16:49
Hi there @ekeeke ,

awesome to see.

Try to register on this site and submit a solution. That way, once we have closed the issue, you will be eligible for the bounty.

**Comment by rtissera** [comment] 2017-08-27 16:53
Great work @ekeeke.
Indeed I missed the big endian platforms :)

**Comment by ekeeke** [comment] 2017-08-27 17:11
To be honest with you, I don't really feel comfortable with that bounty thing. I did not asked any 'bounty' for implementing sega cd support in the first place or for the continued bugfixes since then, which were honestly much more workload than adding this simple feature. If people who use my work want to show their appreciation,  there has always been a donation link on my repository especially for that but I don't feel like getting "paid" by you to fulfill end-users requests.

**Comment by twinaphex** [comment] 2017-08-27 17:15
@ekeeke I am not paying at all, it is the users whom would pay you. You can look at the backers and see that our name does not pop up there.

Anyway, I was just trying to be nice. It is up to you.

**Comment by ekeeke** [comment] 2017-08-27 17:35
I meant you or anyone (I edited previous post) , it's just I don't want people 'paying' me to get features or me using that bountysource thing. I personally think in long term this discourages other developers from releasing any new stuff 'for free' and give end-users the impression they can only get new stuff by offering enough money for it. Once again, I have a donate button on Genesis Plus GX homepage if people want to throw a few bucks to show support for already done and upcoming work, if I wanted to get paid for my hobby, I would have a patreon or a bountysource account.

**Comment by twinaphex** [comment] 2017-08-27 17:48
Fair enough, if that's your stance on it then so be it. Still though, I would really recommend you find some other way to obtain donations other than Paypal. Obtaining donations for emulators is against their Terms of Service, and it's only a matter of time until it will be shut down, and then if your bank is tied to your Paypal account, you will never be able to use it again.

https://yabause.org/2016/05/26/donation-changes/

I also don't see how having a Donation page is any different from Bountysource or Patreon, but I respect your stance nonetheless. I am just warning you against Paypal since it is pretty much a 100% given that it will be shut down.

**Comment by ekeeke** [comment] 2017-08-27 19:33
I appreciate your concern but I really doubt they give a shit now considering it has been running for ten years and I received less than 100 euros in total :-)

And on that regard, I consider this indeed to be very different from a patreon where you get paid every month and have stretch goals to motivate your patrons or bountysource where you setup a price for your contributions to the project.

**Comment by anothername99** [comment] 2017-08-27 19:44
@ekeeke It's up to you. If you want the money, we'll pay you, if not, we won't. :)

**Comment by anothername99** [comment] 2017-08-27 20:02
@twinaphex @rtissera There is more money on this bounty than the beetle-psx CHD bounty and I'm not sure if refunds are a straight-forward thing. So if ekeeke really doesn't want the money, then perhaps we can use this money on that instead.

rtissera could then "start a solution" on this bounty if/when he has implemented CHD support for beetle-psx (but let's wait for @ekeeke 's confirmation first).

**Comment by rtissera** [comment] 2017-08-27 20:53
Well on the PSX the current limitation is no support for subchannels (in CHDMAN)  so libcrypt games won't work except if we hook SBI support to CHD code. 

Another approach is to add a proper CloneCD parser to MAME CHDMAN and get it upstreamed. 

I am also considering improving the libchdr by adding some more high level code in order to ease CHD support into various emulators as suggested by @p1kpin

**Comment by p1pkin** [comment] 2017-08-27 21:11
it is not entirely correct, chdman supports CDRDAO TOC/BIN format, including subchanel data.

**Comment by anothername99** [comment] 2017-08-27 21:28
I would suggest adding .sbi file support to chdman at least. Even if the user only has a cue/bin image, he can get a .sbi file for his game from redump.org. Of course a full CloneCD parser would be even better though.

**Comment by p1pkin** [comment] 2017-08-27 21:41
.sbi ?

**Comment by rtissera** [comment] 2017-08-27 21:45
@p1pkin SBI files are basically patches containing PSX libcrypt protection information (stored in sub channel data).

http://psxdatacenter.com/sbifiles.html

**Comment by p1pkin** [comment] 2017-08-27 21:51
thanks for explanation, sounds like a piece of hack instead of proper subchanel data.

**Comment by rtissera** [comment] 2017-08-27 21:53
It is.

**Comment by ajshell1** [comment] 2017-09-05 15:27
Any progress? It seems as though standalone GPGX now has CHD support. Implementing that into the RA core is an easy $45.

Besides, I already converted all my Sega CD games to CHD.

**Comment by twinaphex** [comment] 2017-09-05 16:25
The problem is that ekeeke doesn't want the money. 

I'd say the best thing we could do is that the backers agree how that money should get reallocated instead, I then send a solution on Bountysource, you agree to the solution, and then I make sure we transfer the money to whatever else needs it. I don't think Bountysource does refunds or anything, and you'd lose 10% as part of transfer fees.

**Comment by anothername99** [comment] 2017-09-05 17:31
@twinaphex Yeah, I agree that we should avoid going the refund route. Are transfers a thing though? I would be fine with that of course. Otherwise maybe ajshell1 could just edit the title and first post on this issue and add a note that the genplusgx is old and doesn't apply.

@ajshell1 CHD already works in the genplusgx libretro core as well, it just needs to be merged and added to the buildbot. Is there anything else you want for RetroArch/libretro that needs funding? If it's something I also want, then I'm in.

**Comment by ajshell1** [comment] 2017-09-05 19:07
@twinaphex @anothername99  I agree with anothername99's idea of editing the title and first post.

Unless anothername99 can come up with a better idea, I'm going to change this to "Add CHD support for Genesis Plus GX and Picodrive".

**Comment by anothername99** [comment] 2017-09-05 19:51
Personally I would like to see a solution to the multi-disc problem. m3u playlists and the like are a bit of a pain, so I'd prefer if there was support for putting every disc in an uncompressed zip file or something like that. With predictable filenames (disc1.chd, disc2.chd, etc) it should work pretty well.

But if you would rather go with Picodrive CHD support, I'm fine with that too. I wonder what the other backer @emarleau thinks though.

**Comment by Awakened0** [comment] 2017-09-05 21:24
I'm getting a crash loading a CHD with the latest Win64 buildbot build (60ca366941ce92d12c51500b32ea9793e743e960). The bin/cue loads fine. Here's a backtrace: https://hastebin.com/aloqesical.tex

**Comment by ekeeke** [comment] 2017-09-06 12:31
Crash is caused by incompatibility between libretro FILE virtualization and libchdr file access. It didn't occured to me because libretro port in my repository is missing all the recent FILE virtualization changes added for UWP support (my repository is actually more than 80 commits behind this repository so please someone submit a pull request to sync everything back properly on both sides, not just libretro side).

This pull request should normally fix it : https://github.com/libretro/Genesis-Plus-GX/blob/master/libretro/libretro-common/include/streams/file_stream_transforms.h

Btw, I'd suggest you give that bounty to @bkoropoff if my refusal is causing you so much issues. Afterall, he is the one who got CHD file support working in retroarch in the end and that's the only thing that matters, right?

**Comment by ajshell1** [comment] 2017-09-06 14:01
@ekeeke Alright. Good to hear. As for the bounty, if @bkoropoff shows up and decides that he wants the money, I will not object to giving it to him.

**Comment by Awakened0** [comment] 2017-09-06 18:33
Ok, with the latest build there's no more crashing and all the official games I tried work perfectly. Sonic Megamix 4.0b won't go past the CD player screen when converted to CHD though. The cue/iso still works fine.

**Comment by bkoropoff** [comment] 2017-09-06 20:10
I just submitted a trivial fix since I happened to be trying out the
feature and dug into the crash out of curiosity.  The bounty should go to
whoever did the actual implementation work.

**Comment by twinaphex** [comment] 2017-09-07 00:17
@bkoropoff The problem with that is that he doesn't feel comfortable taking it, so since Bountysource doesn't do refunds, it still has to go towards somebody otherwise the bounty backers just lose their money altogether.

We are reaching a kind of dead road here. If bkoropoff doesn't want it either, I'd suggest doing what I suggested before where the bounty backers let me claim a solution, then we redistribute the money to another issue of the bounty backer's choosing.

**Comment by anothername99** [comment] 2017-09-07 09:20
@twinaphex Now I get what you mean. I wouldn't mind. If you make a claim, I'll accept. You can then put the money in another bounty, or put it back in the libretro organization, whichever you prefer.

**Comment by ekeeke** [comment] 2017-09-07 12:02
@Awakened0: does it show correct number of tracks in CD player screen and does it let you play audio tracks correctly? Please copy the cue file content so I can see if there are any particularities I might have missed.

**Comment by Awakened0** [comment] 2017-09-07 18:44
@ekeeke, Megamix 4.0b doesn't have any CDDA audio tracks, it uses regular YM2612 for it's BGM. When you download it it doesn't even come with a cue; I just created a basic one back when I needed .cue files for all my Sega CD games to launch through HyperSpin. I already deleted it since I realized I could just load the .iso, but I think it was just a single data track 01 index 00:00 thing. I tried creating a CHD directly from the ISO and that didn't get past the CD player screen either.

**Comment by ekeeke** [comment] 2017-09-07 19:41
It's probably because BIOS expects CD games to have at least one audio track following data track. Fake audio tracks are automatically created in Genesis Plus GX for iso or cue/bin but I didn't bothered doing the same for CHD files,

**Comment by ekeeke** [comment] 2017-09-07 19:41
It's probably because BIOS expects CD games to have at least one audio track following data track. Fake audio tracks are automatically created in Genesis Plus GX for iso or cue/bin but I didn't bothered doing the same for CHD files,

**Comment by Awakened0** [comment] 2017-09-07 19:48
That sounds right. It's not a huge deal to not have that game in CHD format since it's only around 14 MB uncompressed; it'd just be nice to have for consistency's sake.

**Comment by ajshell1** [comment] 2017-09-08 16:08
I'd support giving the bounty money to Twinaphex. I'm sure he can think of a good way to use the money.

**Comment by twinaphex** [comment] 2017-09-08 16:12
Can you link me to the bounty URL from Bountysource?

Also, have the backers decided where the money should go to? Should it go to an existing bounty or should a new one be created, etc?

**Comment by emarleau** [comment] 2017-09-08 17:02
I'm ok to donate the money to libretro.

**Comment by anothername99** [comment] 2017-09-08 20:05
Here is the URL: https://www.bountysource.com/issues/47874325-add-chd-support-for-genesis-plus-gx-and-picodrive

**Comment by twinaphex** [comment] 2017-09-08 20:38
OK, so since all backers agree, I am going to repeat the question I asked above -

'have the backers decided where the money should go to? Should it go to an existing bounty or should a new one be created, etc?'

**Comment by twinaphex** [comment] 2017-09-08 21:00
All three of you can also state individually where your own money should go towards. That might be a better solution vs. having all three of you having to agree on something.

**Comment by ajshell1** [comment] 2017-09-08 21:01
@twinaphex You can have all of my bounty money. Do whatever the hell you want with it.

**Comment by p1pkin** [comment] 2017-09-09 15:56
@ekeeke 
> while original CD-DA format is little endian

afaik data stored at physical CD in big endian. in bit stream most significant bit comes first, least significant bit comes last.
but yes, in common PC CD image formats CD-DA stored as little endian.

**Comment by twinaphex** [comment] 2017-09-09 16:57
I'll close the issue then. People in this thread can still feel free to comment here (if possible) or in another issue, we're closing this just for the bounty proceedings.

**Closed by twinaphex** 2017-09-09 16:57 UTC

**Comment by twinaphex** [comment] 2017-09-28 19:44
@emarleau @anothername99  Can you guys remind me where your money from this bounty should go towards? I will get that done then right now, sorry for the delay.

**Comment by emarleau** [comment] 2017-09-28 19:47
Can you put my money to this bounty please? https://www.bountysource.com/issues/48048939-dynamic-recompiler-305-bounty

**Comment by twinaphex** [comment] 2017-09-28 19:53
@emarleau Done.
