### ISSUE TITLE
Upper buttons (X,Y,Z) does not work in Duke Nukem 3D.

### ISSUE THREAD

**Issue by gogtytsufvhgekwzyuow** [libretro/Genesis-Plus-GX#161] opened 2019-01-17 03:45 UTC
Rom: Duke Nukem 3D (B) [!] ( MD5: 5093AD6641ABB0C3757D24DA094A51E6 )
Settings are explicitly set to "MD Joypad 6 button ". 
Other tested games work fine with 6 buttons, it is the only game with this problem.
The game works as 6 buttons with Picodrive core, with standalone emulators: KegaFusion, Gens, Gens32, and on real hardware.
The behavior confirmed by 4 different people.

**Comment by ekeeke** [comment] 2019-01-20 17:36
Looks like an issue I fixed years ago (see link below) that somehow appeared back again after recent changes to gamepad emulation where I forgot about this particular game and introduced a regression.

https://bitbucket.org/eke/genesis-plus-gx/issues/176/duke-nukem-3d-not-working-with-6b-control

It should be easily fixable though, I will push a commit to my repository when I get some time.

**Comment by ekeeke** [comment] 2019-01-20 17:48
For further reference, here is the commit which broke 6-Button support in this particular game

https://github.com/ekeeke/Genesis-Plus-GX/commits/master/core/input_hw/gamepad.c

The step counter should actually count transition of TH from 0 to 1, not the opposite.

**Comment by hizzlekizzle** [comment] 2019-01-26 22:52
fix merged now, so I'll close this issue. Feel free to reopen if the problem persists.

**Closed by hizzlekizzle** 2019-01-26 22:52 UTC
