### ISSUE TITLE
[Switch] Unable to load CHD file "failed to load content"

### ISSUE THREAD

**Issue by ITotalJustice** [libretro/Genesis-Plus-GX#163] opened 2019-01-25 21:41 UTC
After testing every build, i've found that loading CHD files no longer works with all versions AFTER 01/07/19 (tested up to build 01/25/19).

All newer builds will crash retroarch, then loading anything else on the switch homescreen results in a full crash.

**Comment by cucholix** [comment] 2019-01-28 17:56
@m4xw @natinusala could it be related to the broken chd support in 4DO?

**Comment by natinusala** [comment] 2019-01-28 18:58
Yes, it's probably the same issue

**Comment by natinusala** [comment] 2019-01-29 22:50
The issue was that the linker decided, for some reason, to use the libretro-common of RetroArch instead of the one of the core (remember it's all statically linked). So, as RetroArch wasn't built with `HAVE_CHD`, the core couldn't access CHD functions.

So if we revert this commit, it will break 4DO. The proper fix would be to tell the linker to use the libretro-common _of the core_ and not the one of RetroArch. But this may break RetroArch if the core has made breaking changes to their copy of libretro-common.

**Comment by ekeeke** [comment] 2019-01-29 23:23
Well, looking at the issue report in 4DO-libretro, it seems  it was not fixed by linking with retroarch libchdr so now it looks like you have two cores with broken CHD support instead of just one ;-)
https://github.com/libretro/4do-libretro/issues/119

As said above, forcing Retroarch to statically link its own libchdr object files with any core is not a good solution, especially when it is unsure if this libchdr version is really working with all cores (or even working at all) so this should be reverted.

The solution should rather be to fix 4do specific linking issue so it uses libretro-common functions from its own repository and not the ones from retroarch object files. I don't think you can force the linker to link with the object file you want if two object files define the same symbol (the result is likely it uses the first one that got in the linked object files list, which in this case is retroarch Makefile object files, but this is unsure and might depend on the compiler/linker) so the only solution might be to rename libretro-common functions in core repository that rely on HAVE_CHD being defined so this can only be defined on core Makefile side, not Retroarch.

**Comment by natinusala** [comment] 2019-01-29 23:35
But `intfstream_open` is in RetroArch, and it's used for stuff other than CHD. The issue is not in CHD itself, it's in that particular function.

The linker **will** use the one in RetroArch over the one of the core. Would the solution be to remove the whole intfstream from RetroArch and let it use the one of the core ? What if the core doesn't build it because it doesn't need it ? Undefined reference ? 

No. The solution would be to fix CHD once and for all, PR that to RetroArch and sync the libretro-common repo afterwards.

Or, as you said, rename `intfstream_open` in the core and use this one instead. But that's not a good solution IMO.

**Comment by ekeeke** [comment] 2019-01-29 23:52
Either way, this is not a core issue and Genesis Plus GX is not going to drop its 'own' version of libchdr for libretro-common one (since it's being used for standalone non-libretro ports) so this issue should be closed and the retroarch PR from January reverted until this got sorted out on 4Do-libretro side.

**Comment by natinusala** [comment] 2019-01-30 06:40
I don't say that Genesis Plus GX should drop its own version of libchdr but rather upstream the fixes to RAw if that's possible

**Comment by ekeeke** [comment] 2019-01-30 13:59
I don't think this will work because normally the linker will look at object files from static library ONLY if they export at least one symbol that was marked as unresolved but since retroarch object files are the ones that implement the entry point and call the functions implemented by core object file (libretro API), the core object files will simply be ignored by the linker if they are processed before retroarch object files as there will be no undefined symbols (beside entry point) at the time they are parsed by the linker so you will likely get undefined symbols errors when linking.

A possible (clean but heavy) solution could be to modify retroarch Makefiles (common and platform specific) so libretro-common code (and possibly any other optional library code) get compiled into a static library, then in platform specific Makefile, link that static library in desired order (after core static library for platforms that use static linking with cores).

Another solution (less clean but with more limited impact on retroarch Makefiles) could be to use existing BLACKLIST flag in retroarch platform-specific Makefile to exclude libretro-common object files from the list provided by Makefile.common then re-add them AFTER the core static library in linking list (if they redefine symbols already resolved from core object files, the symbols will simply be ignored with no error message if you use --allow-multiple-definition flag )

**Comment by natinusala** [comment] 2019-01-30 15:24
We took the decision to rewrite the libchdr implementation of libretro-common from upstream to have a working verison of it and fix it once and for all.

In the meantime, I will see if reordering the objects and static library in RetroArch does anything. If it does, we can use that in the meantime. If it doesn't, I'll remove `HAVE_CHD` from RetroArch since 4DO doesn't work anyway (updating libchdr may fix it).

**Closed** 2019-01-30 19:51 UTC
