### ISSUE TITLE
Games that doesn't work on RPI2

### ISSUE THREAD

**Issue by LodanZark** [libretro/Genesis-Plus-GX#34] opened 2015-12-02 17:34 UTC
According to Sega Retro (http://segaretro.org/Genesis_Plus_GX):
"ROM images up to 10 MB (Mortal Kombat II hack Mortal Kombat II Unlimited) (Ultimate Mortal Kombat 3 hacks such as Ultimate Mortal Kombat Trilogy, Mortal Kombat Revelations, Ultimate Mortal Kombat [SMD])"

Games that i've tested over Raspberry Pi Model 2 and haven't worked:
# Mortal Kombat II Unlimited (http://www.romhacking.net/hacks/596/) - Fails to load
# Mortal Kombat Revelations (http://www.romhacking.net/hacks/1826/) - Loads but it crash in middle of a match.
# Ultimate Mortal Kombat Trilogy version 5125 (http://www.romhacking.net/hacks/1059/) - Fails to Load
# Sonic 2 Long version 1.8.1 (https://info.sonicretro.org/Sonic_2_Long_Version) - It works if the name file of the ROM doesn't contain "()" or "[]", for example "Sonic 2 Long Version 1.8.1 (hack)", otherwise it fails to load...

**Comment by ekeeke** [comment] 2015-12-12 09:59
All those hacks should work fine if you disable "68k Address Error" (and eventually enable "Force DTACK) in core settings. 

For the record, those are badly "programmed" hack that fail to work on real hardware because they were only tested on inaccurate emulators.

As for filename issues, there is no restriction in the emulator about that so it's an issue with the frontend you are using.

**Comment by LodanZark** [comment] 2015-12-13 17:34
Thanks, i will give a try ;)

**Comment by ekeeke** [comment] 2015-12-13 20:40
68k address error is what generally causes these hacks to crash and, as said above, it's the core setting that should be disabled. The other one was only mentionned as an additional possible solution.

I've tried those hacks on my standalone port for Wii and they all load fine so, at this point, any games that fail to load on your side is likely because of some issue with RPi frontend,  unrelated to the emulator core itself.

**Comment by LodanZark** [comment] 2015-12-13 20:50
I am using the Retropie distro version 3.2.1 (latest version at this date) for RPi2 with latest version of lr-Genesis-Plus-GX installed, I will try follow your instructions to see if i can solve this.
Thanks very much for your reply

**Comment by LodanZark** [comment] 2015-12-13 21:48
By editing the the retroarch-core-options.cfg file and changing the value of "genesis_plus_gx_addr_error" to "disabled" fixed all issues with: Sonic 2 Long version 1.8.1., Mortal Kombat II Unlimited and Mortal Kombat Revelations. Yet the Ultimate Mortal Kombat Trilogy version 5125 and the same version with extra tracks weren't able to boot.

**Comment by ekeeke** [comment] 2015-12-15 22:17
There is indeed a bug accidentally introduced when adding support for cartridge games using audio CD tracks in https://github.com/ekeeke/Genesis-Plus-GX/commit/a07f7a3d24e77d7a6ebdcbae6ca51bc19c539edb

This is now fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/8a5cce4e8d69a886177390a242f3a6079c478d04, thanks for the report. If you are using it on RPi, this still need to be synced back in libretro repository and recompiled by libretro devs.

As for the 13MB version with extra tracks, it can not work because the max supported ROM size is 10 MB. I think it only works on hacked emulators and not on real hardware either because it uses memory range  that is also used by Mega Drive internal hardware (Z80 & I/O area, VDP area) and is normally not usable for cartridge.

**Comment by LodanZark** [comment] 2015-12-16 00:33
Thank you very much!
Sonic 2 Long 1.81 and mortal kombat 2 unlimited works very well now with genesis_plus_gx_addr_error enabled, and the Mortal Kombat Revelations works fine yet gets often the blue screen with address error by accessing the 00FF233 address which is easily fixed by disable the genesis_plus_gx_addr_error.
I suppose this issue can be closed.

**Comment by ekeeke** [comment] 2015-12-16 07:53
You should be able to close it yourself, I don't have admin power here.

**Comment by LodanZark** [comment] 2015-12-16 14:33
I will close it myself then ;)

**Comment by twinaphex** [comment] 2016-01-13 09:06
@ekeeke I still visit here.

To be honest, it would really help me if you could help out with the Wii version of RetroArch sometime. There are numerous issues we are still having with libogc since Day One and nobody ever bothered to help us. I still care about having RA run well on Wii but I am quite disappointed that no single Wii dev ever bothered to help us when we have asked time and time again to help fix up some of the rough spots.

**Comment by ekeeke** [comment] 2016-01-13 12:34
>Telll me the issues that should be closed on the fork and I'll do it.
I think all the issue reports except the last one can be closed.

>Alternatively, if you don't like the fork repo having an issues section at all, then we could close it if that is what you want. Let me know about that.
Yes, it might be a better idea to have all core issues centralized in my repo.

>Also, on another subject. To be honest, it would really help me and numerous users if you could help out with the Wii version of RetroArch sometime (I think I asked this once before and I didn't get much help then either).

I'm not sure what kind of help you are expecting, I think I already did some code review and gave some advices t but I'm afraid I don't have the time for deeper bug investigation on Wii or submitting code patches. To be honest, I do not even have much free time to work on my own version or for testing things on Wii recently and this is not going to improve this year due to some important family "update"coming in a few weeks  ;-) 

I still read and answer issues reports from time to time or make quick fixes when I can but I don't have much time for "serious" coding anymore.

>I am quite disappointed that no single Wii dev ever bothered to help us when we have asked time and time again to help fix up some of the rough spots.
You have to understand that all the devs who were working on Wii homebrew are now  - for most of them - long gone and left the "scene" long time ago. It's not that nobody wants to help you, it's more than people have their own life priorities and have moved to other things. 


>The issues are input bugs where sometimes the input can repeat itself for one frame, and also a better way to handle resolutions. We sometimes have issues with PAL resolutions.

See, this is also a problem, because these are quite vague requests or hard to reproduce issues.

Like I said, I already had reviewed your code and did not see any problem that could cause the input issues and honestly never noticed any the few times I tried Retroarch on my Wii so it's going to be hard to propose a fix for that without knowing what causes it.

This was some time ago so if the code changed a lot since, I could possibly do another review to see if anything seem wrong to me but, like I said, this is as much as I can do for now.

**Comment by twinaphex** [comment] 2016-01-13 14:21
"Like I said, I already had reviewed your code and did not see any problem that could cause the input issues and honestly never noticed any the few times I tried Retroarch on my Wii so it's going to be hard to propose a fix for that without knowing what causes it."

The buttons get "stuck" for like half a frame at specific intervals. You can easily notice this with any CPS2 game in FB Alpha if you play it for some time with any fighting game. For instance, if you're controlling a character and pressing to the left and then downwards, it could get 'stuck' for like half a frame with 'down' being pressed during that time. Pretty much game-breaking.

"I understand that Retroarch is very important to you" 

I hope you didn't mean this in a patronising way. Because it very much reads to me like that. It's like you say 'oh well you are ridiculous for caring so much about this' and I don't really respect that. If you didn't mean it like that then I apologize for reading it like that but that is how most of the rest of the post reads like 'not worth the time', 'those guys moved on', 'blablabla'.

**Comment by ekeeke** [comment] 2016-01-13 14:59
It was not meant to ridiculing anyone. As for myself, I can perfectly understand caring a lot for the project I 'm working on and being concerned by its quality issues. I was only trying to explain that what you are asking would require much more work than a few programming tips from fellow developers and that people that are unrelated to the project or "retired" from Wii homebrew likely do not have the motivation or time to debug and refactor Retroarch Wii driver for you.

I'm sorry you feel this is "blabla" , I was just trying to be honest regarding your request. As I said, I'm always open for doing code reviews or answering technical questions about Wii programming if I can.

**Comment by twinaphex** [comment] 2016-01-13 15:01
OK thanks for clarifying that. I felt a bit bad about it if that was honestly the way you meant it. Good to hear it was not meant like that.

**Comment by ekeeke** [comment] 2016-01-14 16:08
I had a quick look to https://github.com/libretro/RetroArch/blob/wiiusb_hid_hotplugging/input/drivers_hid/wiiusb_hid.c

The code is quite complex and I don't have much experience with libogc USB driver so I could not comment on USB_ function calls but I have noticed at least 3 things that seem wrong to me in the code:

1) "wiiusb_hid_change_thread" is locking "change_lock" mutex before waiting for "change_cond" signal from "wiiusb_hid_changenotify_cb" however this callback is itself first trying to lock "change_lock" mutex before sending back "change_cond" signal so it seems to me it would cause both to get blocked on the same mutex.

2) "wiiusb_hid_in_device_ids" is used in "wiiusb_hid_change_thread" to search registered device ID in "current_device_ids" array but it only searchs for MAX_PADS (4) entries while the array has MAX_USER (16) entries.

3) at the end of "wiiusb_hid_change_thread", you are adding new devices only if their device ID is equal to current_dev->device.device_id which makes no sense since :+1: 

-  current_dev is supposed to be NULL when exiting the loop above
-  you want to add devices that have not yet been registered

**Comment by netux79** [comment] 2016-01-14 18:46
Thanks @ekeeke, I will check it out your comments!

**Comment by ekeeke** [comment] 2016-01-15 12:25
I took some time to have a look at https://github.com/libretro/RetroArch/blob/master/gfx/drivers/gx_gfx.c for potential issues:

1) in "gx_set_video_mode", I don't think it's a good idea to disable interrupts while reconfiguring all the video stuff, this should only be done normally for a short time period and it might be the cause of video corruption issue when switching mode. Therefore, I would remove calls to

     _CPU_ISR_Disable(level);

     _CPU_ISR_Restore(level);

in this function and instead add a call to VIDEO_WaitVSync() after the FIRST call to VIFlush() to ensure all the changes are done outside the display period.

2) When changing from interlaced to non-interlaced or the opposite, it is generally required to wait for at least two frame before timings are stabilized so you should all TWO calls to VIDEO_WaitVSync()  after the LAST call to VIFlush() in "gx_set_video_mode"

3) In "gx_set_video_mode", the following code is unnecessary

    if (modetype == VI_NON_INTERLACE && lines > max_height / 2)
        gx_mode.xfbHeight = max_height / 2;
    else if (modetype != VI_NON_INTERLACE && lines > max_height)
        gx_mode.xfbHeight = max_height;
     
since the code just above:

    if (lines <= max_height / 2)
    {
        modetype = VI_NON_INTERLACE;
        viHeightMultiplier = 2;
    }
    else
    {
        modetype = (progressive) ? VI_PROGRESSIVE : VI_INTERLACE;
    }

    if (lines > max_height)
        lines = max_height;

ready take care about the limits for the "lines" value

4)  in "setup_video_mode", the following condition

    if (!gx->framebuf[0])
    {
        unsigned i;
        for (i = 0; i < 2; i++)
            gx->framebuf[i] = MEM_K0_TO_K1(
            memalign(32, 640 * 576 * VI_DISPLAY_PIX_SZ));
    }

always occurs since this function is only called once by "gx_init" on driver init which beforehand allocate the "gx" structure so gx->framebuf[i] will always be unallocated (NULL) at this point.

5) in "setup_video_mode", the call to

    VIDEO_GetPreferredMode(&gx_mode)

is unnecessary since this is done automatically in "gx_set_video_mode" when lines and width are set to zero which is the case here.

6) in "init_texture", the GX limitation that texture width and height must be multiple of 8 

    width &= ~3;
    height &= ~3;

is only when pixels use 16-bit format (RGB565 or RGB5A3). If RGB32 is used (RGBA8), the limitation is that the width and height should be multiple of 4 pixels. I am not sure if any core use RGB32 format while using uncommon video buffer size but you never know.


7) in "init_vtx" function, the following condition:
     if (gx->scale != video->input_scale || gx->rgb32 != video->rgb32)
     {
          RARCH_LOG("[GX] reallocate texture\n");
          free(g_tex.data);
          g_tex.data = memalign(32,
          RARCH_SCALE_BASE * RARCH_SCALE_BASE * video->input_scale *
          video->input_scale * (video->rgb32 ? 4 : 2));
          g_tex.width = g_tex.height = RARCH_SCALE_BASE * video->input_scale;
          if (!g_tex.data)
          {
               RARCH_ERR("[GX] Error allocating video texture\n");
               exit(1);
          }
     }

always occur since this function is only called once by "gx_init" on driver init which beforehand allocate the "gx" structure so gx->scale and gx->rgb32 will always be uninitialized (0) at this point

7) "gx" pointer is unallocated in "gx_free" function but gx->framebuf[i] that were allocated in "setup_video_mode" (cf. 4)  are never unallocated, which could cause memory leak in case "gx_init"/"gx_free" is called multiple times by retroarch.

**Comment by netux79** [comment] 2016-01-15 15:17
Thanks @ekeeke , I'm aware of the interrupt disabling issue and also about the need of waiting for the vertical retrace while changing resolutions and I also think this is in part the cause of the video corruption issue. The other code you point as unnecessary we'll need to check as the resolution is not changed once at startup in RA but each time you change cores, however these are pretty good catches as I didn't know about the texture width to be multiple of 8.

Regarding the code duplication, that was done since long time ago when the RA Wii version started (I guess) and personally I don't think that's necessary and it would be a better idea to stick with the original libogc functions.

I will work on the controls stuff first and then when I have time I will try these last comments from you for the gfx stuff.

Thanks a lot for the input!

**Comment by ekeeke** [comment] 2016-01-15 15:34
>The other code you point as unnecessary we'll need to check as the resolution is not changed once at startup in RA but each time you change cores

If you mean the part about "VIDEO_GetPreferredMode(&gx_mode)", it's just that this function is already called in "gx_set_video_mode" so basically it's being called twice for nothing.

If you mean the part about gx parameter condition checks, it does not matter if or when resolution is changed, the point is that those bits of code are only called from "gx_init" after it allocates a new gx structure pointer so any gx->... parameter will always be reseted at this point.
The fact gx->framebuffer[i] is never unallocated but the gx "parent" is (within gx_free) is also a problem that will likely cause memory issues after a few times reloading cores (as I assume this is what calls gx_free / gx_init). 

To finish my "code review", here are some comments on https://github.com/libretro/RetroArch/blob/master/input/drivers_joypad/gx_joypad.c

Nothing much but  here you go for completeness...

1) The following code in "gx_joypad_poll"

    ls_y = (int16_t)PAD_StickY(port) * -256;
    rs_y = (int16_t)PAD_SubStickY(port) * -256;

will cause an overflow if the value returned from one of the sticks is -128. The y value would be max negative value instead of desired max positive value. This probably never occurs since the values returned from GX analog sticks are likely limited and never reach int8_t limit but you never know.

2) PAD polling is usually done juqt before VSYNC so you should add a call to "VIDEO_WaitVSync()" before the first call to "gx_joypad_poll()" in " gx_joypad_init" function

3) Try initializing the data format after having initialized WPAD in " gx_joypad_init" with

     WPAD_SetDataFormat(WPAD_CHAN_ALL,WPAD_FMT_BTNS_ACC_IR);

even if you are not using IR or motion because it will sets the controller report mode to "CONTINUOUS" instead of the controller only reporting when a button is pressed. It should not matter in theory but you might want to try that to see if this fixes the "button sticking" bug as all homebrew emulator that I know of use that mode.

**Closed** 2017-09-07 00:15 UTC
