### ISSUE TITLE
Duke Nukem 3D -invisible sprites + a sprite corruption

### ISSUE THREAD

**Issue by gogtytsufvhgekwzyuow** [libretro/Genesis-Plus-GX#162] opened 2019-01-22 18:25 UTC
Many sprites often become invisible in GenesisPlusGX.

The bug can be immediately detected at the first second of the first demo:
Picodrive: http://funkyimg.com/i/2Qs2V.jpg
KegaFusion: http://funkyimg.com/i/2Qs2W.jpg
Gens: http://funkyimg.com/i/2Qs2Z.jpg
GenesisPlusGX (incorrect behavior): http://funkyimg.com/i/2Qs2P.jpg

When it happens, these sprites become invisible though entire game: 
- Medkits +10 , +30, +100 (portable)
- Space Suite
- Ammo for pistol, shotgun, chaingun, rpg, devastator
- Pipebombs
- also Devastator sprite becomes corrupted (screenshots from different places in the game):
http://funkyimg.com/i/2Qs24.jpg
http://funkyimg.com/i/2Qs2n.jpg
http://funkyimg.com/i/2Qs2v.jpg

The bug does not always happen and can disappear after few resets but it tedious - one time to remove the bug it takes about 100 resets to me.

P.S. Looks like this game is cursed with this core.

**Comment by ekeeke** [comment] 2019-01-22 20:24
Weird, I never encountered this bug and does not seem to be able to reproduce it. Looks like ROM, RAM or VRAM got corrupted for some reason.

Have you enabled any retroarch-specific feature like run-ahead, rewind or cheats by any chances?

**Comment by gogtytsufvhgekwzyuow** [comment] 2019-01-23 02:55
> run-ahead
tried it on/off - does not affect this bug

> achievements
tried it on/off - does not affect this bug

> rewind 
disabled

> cheats
disabled

---

Asked another person about it - he has the same problem with GenesisPlusGX. Will try to ask some more.

**Comment by gogtytsufvhgekwzyuow** [comment] 2019-01-23 06:01
Accidentally found after some more testing: after you use the ingame save (you do not even need to load) - the bug can disappear.
The first pistol's ammo after the second door.
Before saving: http://funkyimg.com/i/2QsCX.jpg
After saving: http://funkyimg.com/i/2QsD1.jpg

**Comment by gogtytsufvhgekwzyuow** [comment] 2019-01-23 10:55
@ekeeke After asked 3 other people - everybody confirmed that they have invisible armor at the start of the demo with GPGX. And visible with Picodrive. Strange that you not able to reproduce it.

**Comment by ekeeke** [comment] 2019-01-26 17:39
Fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/32079418a9c86caa7eb3ca62278df08bf9c0de69

Please close this issue (and also https://github.com/libretro/Genesis-Plus-GX/issues/161) once it is pulled into libretro repository

**Comment by hizzlekizzle** [comment] 2019-01-26 22:52
merged now, so I'll close this issue. Feel free to reopen if the problem persists.

**Closed by hizzlekizzle** 2019-01-26 22:52 UTC
