### ISSUE TITLE
[RPi3] Error compiling from the source

### ISSUE THREAD

**Issue by LodanZark** [libretro/Genesis-Plus-GX#89] opened 2017-07-26 14:03 UTC
Couldn't compile the genesis plus gx from the source :(
the log it's in the followed link:

[rps_2017-07-26_135541.log.gz](https://github.com/libretro/Genesis-Plus-GX/files/1176817/rps_2017-07-26_135541.log.gz)

**Comment by obsidianspider** [comment] 2017-07-26 17:11
I'm noticing the same thing on GalliumOS.

[rps_2017-07-26_130708.log.gz](https://github.com/libretro/Genesis-Plus-GX/files/1177465/rps_2017-07-26_130708.log.gz)

**Comment by joolswills** [comment] 2017-07-26 17:50
A new commit was made 4 hours ago (3b5b5e230973cf012e372b8f696c9f81b330234a)  - still errors for me but the problem is now this:

```
In file included from ./libretro/osd.h:54:0,
                 from core/shared.h:10,
                 from core/state.c:39:
./libretro/libretro-common/include/streams/file_stream_transforms.h:42:1: error: duplicate ‘static’
 static INLINE RFILE* rfopen(const char *path, char *mode)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:57:1: error: duplicate ‘static’
 static INLINE int rfclose(RFILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:62:1: error: duplicate ‘static’
 static INLINE long rftell(RFILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:67:1: error: duplicate ‘static’
 static INLINE int rfseek(RFILE* stream, long offset, int origin)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:72:1: error: duplicate ‘static’
 static INLINE size_t rfread(void* buffer,
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:78:1: error: duplicate ‘static’
 static INLINE char *rfgets(char *buffer, int maxCount, FILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:83:1: error: duplicate ‘static’
 static INLINE size_t rfwrite(void const* buffer,
 ^~~~~~
In file included from ./libretro/osd.h:54:0,
                 from core/shared.h:10,
                 from core/genesis.c:42:
./libretro/libretro-common/include/streams/file_stream_transforms.h:42:1: error: duplicate ‘static’
 static INLINE RFILE* rfopen(const char *path, char *mode)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:57:1: error: duplicate ‘static’
 static INLINE int rfclose(RFILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:62:1: error: duplicate ‘static’
 static INLINE long rftell(RFILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:67:1: error: duplicate ‘static’
 static INLINE int rfseek(RFILE* stream, long offset, int origin)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:72:1: error: duplicate ‘static’
 static INLINE size_t rfread(void* buffer,
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:78:1: error: duplicate ‘static’
 static INLINE char *rfgets(char *buffer, int maxCount, FILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:83:1: error: duplicate ‘static’
 static INLINE size_t rfwrite(void const* buffer,
 ^~~~~~
Makefile.libretro:371: recipe for target 'core/state.o' failed
make: *** [core/state.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ./libretro/osd.h:54:0,
                 from core/shared.h:10,
                 from core/loadrom.c:41:
./libretro/libretro-common/include/streams/file_stream_transforms.h:42:1: error: duplicate ‘static’
 static INLINE RFILE* rfopen(const char *path, char *mode)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:57:1: error: duplicate ‘static’
 static INLINE int rfclose(RFILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:62:1: error: duplicate ‘static’
 static INLINE long rftell(RFILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:67:1: error: duplicate ‘static’
 static INLINE int rfseek(RFILE* stream, long offset, int origin)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:72:1: error: duplicate ‘static’
 static INLINE size_t rfread(void* buffer,
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:78:1: error: duplicate ‘static’
 static INLINE char *rfgets(char *buffer, int maxCount, FILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:83:1: error: duplicate ‘static’
 static INLINE size_t rfwrite(void const* buffer,
 ^~~~~~
Makefile.libretro:371: recipe for target 'core/genesis.o' failed
make: *** [core/genesis.o] Error 1
Makefile.libretro:371: recipe for target 'core/loadrom.o' failed
make: *** [core/loadrom.o] Error 1
In file included from ./libretro/osd.h:54:0,
                 from core/shared.h:10,
                 from core/system.c:42:
./libretro/libretro-common/include/streams/file_stream_transforms.h:42:1: error: duplicate ‘static’
 static INLINE RFILE* rfopen(const char *path, char *mode)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:57:1: error: duplicate ‘static’
 static INLINE int rfclose(RFILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:62:1: error: duplicate ‘static’
 static INLINE long rftell(RFILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:67:1: error: duplicate ‘static’
 static INLINE int rfseek(RFILE* stream, long offset, int origin)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:72:1: error: duplicate ‘static’
 static INLINE size_t rfread(void* buffer,
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:78:1: error: duplicate ‘static’
 static INLINE char *rfgets(char *buffer, int maxCount, FILE* stream)
 ^~~~~~
./libretro/libretro-common/include/streams/file_stream_transforms.h:83:1: error: duplicate ‘static’
 static INLINE size_t rfwrite(void const* buffer,
 ^~~~~~
Makefile.libretro:371: recipe for target 'core/system.o' failed
make: *** [core/system.o] Error 1
```

this is due to INLINE being defined as `-DINLINE="static inline"`

this patch fixes it 

```
diff --git a/libretro/libretro-common/include/streams/file_stream_transforms.h b/libretro/libretro-common/include/streams/file_stream_transforms.h
index bf7b6a9..40dfa00 100644
--- a/libretro/libretro-common/include/streams/file_stream_transforms.h
+++ b/libretro/libretro-common/include/streams/file_stream_transforms.h
@@ -39,7 +39,7 @@ RETRO_BEGIN_DECLS
 #define fgets rfgets
 #define fwrite rfwrite
 
-static INLINE RFILE* rfopen(const char *path, char *mode)
+INLINE RFILE* rfopen(const char *path, char *mode)
 {
    unsigned int retro_mode = RFILE_MODE_READ_TEXT;
    if (strstr(mode, "r"))
@@ -54,33 +54,33 @@ static INLINE RFILE* rfopen(const char *path, char *mode)
    return filestream_open(path, retro_mode, -1);
 }
 
-static INLINE int rfclose(RFILE* stream)
+INLINE int rfclose(RFILE* stream)
 {
    return filestream_close(stream);
 }
 
-static INLINE long rftell(RFILE* stream)
+INLINE long rftell(RFILE* stream)
 {
    return filestream_tell(stream);
 }
 
-static INLINE int rfseek(RFILE* stream, long offset, int origin)
+INLINE int rfseek(RFILE* stream, long offset, int origin)
 {
    return filestream_seek(stream, offset, origin);
 }
 
-static INLINE size_t rfread(void* buffer,
+INLINE size_t rfread(void* buffer,
    size_t elementSize, size_t elementCount, RFILE* stream)
 {
    return filestream_read(stream, buffer, elementSize*elementCount);
 }
 
-static INLINE char *rfgets(char *buffer, int maxCount, FILE* stream)
+INLINE char *rfgets(char *buffer, int maxCount, FILE* stream)
 {
    return filestream_gets(stream, buffer, maxCount);
 }
 
-static INLINE size_t rfwrite(void const* buffer,
+INLINE size_t rfwrite(void const* buffer,
    size_t elementSize, size_t elementCount, RFILE* stream)
 {
    return filestream_write(stream, buffer, elementSize*elementCount);
```

(and it compiles and links fine then)

Building on Ubuntu 17.04 / x86_86 /

**Comment by esmith13** [comment] 2017-07-26 22:40
Can't compile from source. Same error as above. RetroPie_x86 on Linux Mint 18.2

**Comment by joolswills** [comment] 2017-07-27 13:35
@twinaphex committed an alternative fix - should build now.

**Comment by obsidianspider** [comment] 2017-07-27 14:10
Confirmed that the fix @joolswills mentioned seems to have resolved the issue. I was able to successfully build on GalliumOS 2.1 x86_64

**Comment by LodanZark** [comment] 2017-07-27 14:15
I confirmed too, build successfully compiled on RPi3

**Comment by ekeeke** [comment] 2017-09-07 07:32
This can be closed

**Closed** 2017-09-07 14:07 UTC
