### ISSUE TITLE
[Feature Request] Multi-Disc Support

### ISSUE THREAD

**Issue by klepp0906** [libretro/Genesis-Plus-GX#209] opened 2020-03-11 10:38 UTC
Wow, i searched and expected this to be an already up and running issue.   yet here we are.

So the conundrum thats created between needing to use genesis plus and picodrive, relative to the features each is lacking complementing one another in the worst way - would be great to have worked out.

This can helped strongly by getting some multi disc support into genesis plus.

I'd love to keep picodrive purely for 32x and 32x  variants of sega cd games (as getting that into genesis plus is probably a much bigger ask) but the problem at current is that youre stuck with most of your collection as chd, but forced to keep anything multi disc as bin+cue for starters.

furthermore even if that wasnt the case, picodrive being the only core that supports 32x would still require 1 single game to stay as bin/cue (farenheit) cause it requires both segacd and 32x discs to run.  (until picodrive gets chd support, that request has long been in)  Regardless, this is going off into left field.

Genesis plus is a great core, and multi-disc (and perhaps m3u support) is largely all that its lacking.

**Comment by ekeeke** [comment] 2020-04-15 07:46
There is already a running issue actually, in my own repository: https://github.com/ekeeke/Genesis-Plus-GX/issues/51

It does not seem anyone have put any serious work in it though.

**Comment by klepp0906** [comment] 2020-04-15 10:55
ah, and so it is.  i even posted there.   been some years, things move fast and the memory isnt so great these days what with toddlers blowing up my solitude :P  

hopefully someone with the ability does something with it, would certainly streamline the genesis platform under libretro to a larger degree. 

someone there mentioned it should be easy to do - course im the farthest thing from the authority on that so lol.

**Comment by televandalist** [comment] 2020-04-24 08:16
@klepp0906 I put a bounty on this issue, should have I put it on the one in your repo? 🤔

**Comment by klepp0906** [comment] 2020-04-24 12:01
thats a question for @ekeeke  

can always reference this issue or vice versa.   Thank you on the bounty.  I'll likely put in when I can.  Times are a bit tight atm.  Partially due to coronavirus, and partially due to my awesome ignorance in that trampolines need to be anchored into the ground.

we had a wind storm and it literally picked it up and threw it from 30 feet away into the back of my house.   Smashed it to all hell >.<   

wont make that mistake again lol.

**Comment by ekeeke** [comment] 2020-05-30 13:38
Support for disk control interface and m3u file list in libretro port was added by https://github.com/ekeeke/Genesis-Plus-GX/commit/82c4821503b576faf38b39ee10f7139748f8671c
in my repository.

As usual, you can test the win32 build which was updated there until this get backported in libretro repository: https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genesis_plus_gx_libretro.dll

As mentioned in the original issue report, there are a few limitations I noticed with Retroarch 1.8.5 that libretro devs might want to consider:

1/ disk control interface only let you add a new disk when the current disk status is set to 'not ejected', which can be problematic with Sega CD games since the disk tray is automatically opened by the BIOS when disk swapping is required so, when you want to manually add disks, you either need to do it in the CD player interface on boot (then swap back to the first disk) before the game is started, or, when asked by the game, you first need to close the disk tray, then add the new disk, then close disk tray again since it was re-opened by retroarch when adding new disk. Note that the latter won't work with some games (like Sherlock Holmes 2) which automatically check the disk as soon as disk tray is closed and re-open disk tray automatically if it is not the expected disk. Obviously, this is easily fixable by using m3u file list to automatically add all disks when the game is loaded, but it still can be annoying for people who want to use Retroarch interface to add new disks.

2/ although "m3u" file extension was added in the "valid_extensions" field returned by retro_get_system_info function ( see https://github.com/ekeeke/Genesis-Plus-GX/blob/master/libretro/libretro.c#L2190 ), it seems like these infos are completely ignored by Retroarch as it is impossible to load a m3u file in Genesis Plus GX core unless you modify the "genesis_plus_gx_libretro.info" file located under /info in your Retroarch installation to modify the supported extension list in there. Again, I don't know if this is expected behavior, but it seems quite odd to me that you have to rely on external infos to let you load a file supported by the core.

**Comment by bslenul** [comment] 2020-05-30 22:07
Awesome news! 👍 

> which can be problematic with Sega CD games since the disk tray is automatically opened by the game (using a BIOS command) when disk swapping is required

Oooh, that explains the issue I posted in the PicoDrive issue board! I thought it was an issue with the core...

> Note that this won't work with some games (like Sherlock Holmes 2) which automatically check the disk as soon as disk tray is closed and re-open disk tray automatically if it is not the expected disk, making it impossible to add the disk when the game asks for it.

And that's the game I used to illustrate the issue: https://www.youtube.com/watch?v=TRRygoBUSNM

Just tried with your new version of GPGX and it also works for me, and I was able to load 3rd case (which asks for Disc 2) with no issue, it still feels a bit weird to close first, then re-enter the Disc Control menu but it works.

This is exactly what I did:
* Without .m3u (exact same process I use in the video):
    * Load the game and select 3rd case.
    * Game will ask for Disc 2, so `Quick Menu > Disc Control > Insert Disc`, game resumes.
    * Re-enter Disc Control menu then click `Load New Disc` and select Disc 2 file.
    * Press B button and it loads fine :) 
* With .m3u (much easier):
    * Load the game and select 3rd case.
    * Game will ask for Disc 2, so `Quick Menu > Disc Control` and you just have to change the disc index and click `Insert Disc`.
    * You don't even have to press any button for some reason, the case will start automatically.

**Comment by Sanaki** [comment] 2020-05-31 00:37
Just built the core from upstream and tested Penn & Teller's Smoke and Mirrors via m3u. Works exactly as described above (though that game requires pressing start to scan the new disc). Works exactly as expected, really.

**Comment by ekeeke** [comment] 2020-06-09 20:56
I have looked a bit in retroarch source code and found the code responsible for the first limitation I noticed, i.e the impossibility to add a new disk when the tray is opened.

https://github.com/libretro/RetroArch/blob/master/menu/menu_displaylist.c#L3543

Looking at the comment, it seems intentional but that restriction looks not really necessary to me and more like an optimization assuming specific use case for disk append but forgetting about cores with emulated games that have the possibility to automatically eject the tray by themselves when loading a new disk is required. It seems like removing this limitation is simple enough but maybe we should first ask @jdgleaver as it seems he was the one who coded the disk options menu.

**Comment by jdgleaver** [comment] 2020-06-10 09:15
@ekeeke While I could certainly modify the disk control interface to support 'inserting' disks while the tray is open, I am reluctant to make any changes that increase the visibility of the `Load New Disc` option. This is an obsolete legacy codepath that is broken by design (it causes more problems than it solves), and no-one should ever use it. I wanted to remove it completely, but this would have generated too many complaints from the peanut gallery...

M3U playlists should always be used for swapping disks with any core. It's great that you added support for this! Regarding the info files - I can understand that it seems odd, but it's a frontend efficiency-related thing (we don't want to have to load a dynamic library just to see what extensions it supports...). Once your changes get added to the libretro repo, the info file should get updated almost immediately.

TBH, I'm not sure how to handle the `Load New Disc` issue now... I don't want to dirty up the interface, but I can appreciate the confusion faced by inexperienced users running Sega CD content. I need to think about this some more...

**Comment by ekeeke** [comment] 2020-06-10 11:28
>TBH, I'm not sure how to handle the Load New Disc issue now... I don't want to dirty up the interface, but I can appreciate the confusion faced by inexperienced users running Sega CD content. I need to think about this some more...

Well, the thing is, this option is already in the menu, just visible only when the virtual tray is closed, which is kinda confusing as it makes more sense from user perspective to load a new disk when the tray is open (it's just that for some reason, that action is designed to automatically open the virtual tray first by default).

However, from emulator point of view, it's not really a good idea to cycle between 'tray close' and 'tray open' statuses without running the emulator in between (which the 'Load New Disk' option is doing). Indeed, with current behavior, an emulator would not even notice the disc was swapped and will try to continue reading from the new disk as if it was still the previous one, which could lead to some emulation issues (maybe that's what you meant by broken design ?).

So it would make more sense to me if you want to keep that option for legacy but restrict its use, to make it visible only when disk is already ejected, thus the opposite of current behavior.

**Comment by jdgleaver** [comment] 2020-06-17 11:09
Okay, this PR should address the `Load New Disc` issue: https://github.com/libretro/RetroArch/pull/10865

**Comment by bslenul** [comment] 2020-06-17 11:59
Tested and confirmed working on my PicoDrive issue: https://streamable.com/8x5uhu

Video was made using PicoDrive core but I tested it with GPGX and it works great too, tested with Sherlock Holmes and Night Trap :)

**Comment by bslenul** [comment] 2020-09-13 11:45
Hey :) 

Sorry to be that guy, but is there any reason (other than life/personal stuff of course) why the "Disc Control" changes are still not available in the libretro repo? It seemed to work perfectly fine last time I tried so I'm a bit surprised. Still in WIP maybe?

Not trying to push anything (can't say I'm a fan of the Sega-CD library, and the few I like are single disc games anyway :p), just being curious!

**Comment by 0x90shell** [comment] 2021-02-02 07:46
@jdgleaver Your change was merged, but it seems the m3u support in @ekeeke forked repo has not been committed into libretro. Any idea how we get maintainers to pull the m3u support in? At a glance I don't see the maintainers listed anywhere.

**Closed** 2021-03-01 12:36 UTC

**Comment by Sanaki** [comment] 2021-09-30 00:03
@ekeeke Looks like I put a bounty on this issue and forgot about it, seems that's your right to claim at your leisure.
https://www.bountysource.com/issues/90103923-feature-request-multi-disc-support
